# Determine the communication protocol and its parameters
esp_protocol: SPI # Options: I2C, SPI, CAN, UART
stm_protocol: UART # Options: I2C, SPI, CAN, UART
i2c_esp_config:
  address: 0x40
  bus: 1
spi_esp_config:
  register: 0xb0
  address: 0x68
  frequency: 4000000   # 4 MHz
  data_size: 40
  bus: 0
  device: 0
uart_esp_config:
  port: /dev/ttyUSB0
  baudrate: 115200
  timeout: 0.5
i2c_stm_config:
  address: 0x38
  bus: 1
spi_stm_config:
  register: 0xb0
  address: 0x68
  frequency: 500000
  data_size: 40
  bus: 0
  device: 1
uart_stm_config:
  port: /dev/ttyUSB0
  baudrate: 115200
  timeout: 0.5

# copy the previous protocols and repeat for any other communication protocols needed

