REAR_LEFT_MOTOR:
  MIN_SPEED: 300
  MAX_SPEED: 800
  MIN_RPM: -8.5
  MAX_RPM: 8.5
  SIDE: left
  LOCATION: rear
  DIR_PIN: 6
  PWM_PIN: 7

REAR_RIGHT_MOTOR:
  MIN_SPEED: 300
  MAX_SPEED: 800
  MIN_RPM: -8.5
  MAX_RPM: 8.5
  SIDE: right
  LOCATION: rear
  DIR_PIN: 4
  PWM_PIN: 5 



