stereo_camera:
  index: /dev/video0
  width: 640
  height: 480
  fps: 20
  port: 8081
  format: MJPG
  calibration: NONE
  calibration_type: STANDARD
  is_stereo: true
  baseline: 0.13
  focal_length_pixels: 783
  disparity_offset: 42.14
  auto_exposure: 0.25
  exposure: -6
  autofocus: 0
